### ISSUE TITLE
open_account should check initial_balance for Negative Or Zero Amount as well

### ISSUE THREAD

**Issue by omac777** [awto-rs/awto-es#2]
I looked at the example.  It's straightforward.  Well done.  In bank_account.rs, I noticed you did some Negative or Zero Amount checks for withdraw and deposit, but I believe you should be doing the same for open_account as well.  Thank you.

**Comment by tqwewe** [comment]
Ah good catch, thats true!

**Comment by tqwewe** [comment]
Fixed in https://github.com/thalo-rs/thalo/commit/9ce356a6f520ad8ae506211b7c9afde9b4e4797a 👍
